# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

![datatypes.png](attachment:datatypes.png)

In [1]:
import numpy as np

In [3]:
# A variavel x e criada como um float de 32 bits com 1 bit para representar se ele
# e positivo ou negativo, 8 bits para representar o seu expoente e 23 bits para 
# representar a mantissa
x = np.float32(1.0)
x

1.0

In [4]:
# A variavel y e criada como um int32 bits que consegue representar numeros inteiros
# que vao de -2147483648 ate 2147483647
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [6]:
# Cria um array que representa o intervalo aberto [0,3[ que guarda valores inteiros
# do tipo unsigned int de 8 bits, portanto em cada espaco do array sao possiveis
# armazenar numeros que vao de 0 ate 255
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [9]:
# Cria um array com os numeros [1, 2, 3] e esses numeros sao representados por
# um float de 32 bits com, 1 bit para sinal, 8 bits para o expoente e 23 bits para
# a mantissa
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

In [14]:
# Retorna o array z que guarda inteiros para um array zf que guarda float de 64 bits
zf = z.astype(float)
print(type(zf[0]))

<class 'numpy.float64'>


In [15]:
# Retorna o array z que guarda inteiros para um array zi que guarda inteiros de 8 bits
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [16]:
# Verifica qual e o tipo de dado que o array guarda
z.dtype

dtype('uint8')